[package]
name = "rust_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmf_crowdsim = { path = '/home/arjo/workspaces/rust/rmf_crowdsim/rmf_crowdsim/' }

[lib]
crate-type=["staticlib"]